#! /bin/sh

do_start() {
    iptables -I INPUT 4 -i docker0 -j ACCEPT
    docker run --privileged=true -p 3030:3030 --name lf-smashing -v /opt/smashing-data:/opt/dashboard_config -t devopsobj/liferay-smashing
}

do_stop() {
    docker stop lf-smashing
    docker rm lf-smashing
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
    do_start
    ;;
  update)
    do_stop
    docker pull devopsobj/liferay-smashing
    do_start
    ;;
  *)
    echo "Usage: /etc/init.d/dashboard-service {start|stop|restart|update}"
    exit 1
    ;;
esac

exit 0

