#! /bin/sh

SCRIPT_NAME=$(readlink -f $0)
CONTAINER=lf-sonar
IMAGE=devopsobj/sonar-with-mariadatabase
PORTS="-p 9000:9000 -p 3306:3306"
VOLUMES="-v /opt/sonar-data:/opt/sonarqube/data  -v /opt/sonar-mysql:/var/lib/mysql"

do_start() {
    docker rm -f $CONTAINER >/dev/null 2>&1
    docker run  --name $CONTAINER $PORTS $VOLUMES  -it $IMAGE
}

do_stop() {
    docker stop $CONTAINER
    docker rm -f $CONTAINER 2>/dev/null
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
    do_start
    ;;
  update)
    do_stop
    docker pull $IMAGE
    do_start
    ;;
  *)
    echo "Usage: $SCRIPT_NAME {start|stop|restart|update}"
    exit 1
    ;;
esac

exit 0

